id: I88334B33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:45:59+00:00'
last_modified: '2022-06-09T07:45:52.799030+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5260
  title: གཉན་རིམས་གསོ་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    03A9:
      image_group_id: I1KG5283
      title: Volume 1 of gnyan rims gso ba
      total_pages: 196
      order: 1
      base_file: 03A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
