id: P007939
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:50:30.097376
source_metadata:
  id: bdr:W1KG5260
  title: གཉན་རིམས་གསོ་བ
  author: ''
  volumes:
    01d23c9b79c64d8a920a78909fffe6de:
      image_group_id: I1KG5283
      title: Volume 1 of gnyan rims gso ba
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
