id: P007939
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5260
  title: གཉན་རིམས་གསོ་བ
  author: ''
  volumes:
    fbaf9412a6c948cc9e810dbd98506f0b:
      image_group_id: I1KG5283
      title: ''
      volume_number: 1
      total_pages: 196
ebook_metadata:
  title: གཉན་རིམས་གསོ་བ
  author: ''
  sku: P007939
  cover: cover.jpg
  layers:
  - pagination
