id: opecha:P007939
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5260
  title: གཉན་རིམས་གསོ་བ
  volume:
    01d23c9b79c64d8a920a78909fffe6de:
      image_group_id: I1KG5283
      title: Volume 1 of gnyan rims gso ba
      volume_number: 1
      total_pages: 196
  author: ''
ebook_metadata:
  title: གཉན་རིམས་གསོ་བ
  author: ''
  sku: P007939
  cover: cover.jpg
  layers:
  - pagination
